const $=id=>document.getElementById(id),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,d=0)=>v==null?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:d}),money=v=>v==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(v);
let catalog,definition,session=null,frames=[],playing=false,pending=false,timer=null,selected=null,experiment=null,evidence=null;
const stateNames=['Qualification queue','Qualifying','Design queue','Designing','Capacity allocation','Awaiting equipment','Installation queue','Installing','Active','Lost'];
const types=['Enterprise AI','High-density AI','Distributed inference'];const group=s=>s<4?'l-commercial':s<6?'l-waiting':s<8?'l-install':s===8?'l-active':'l-lost';
function notice(s=''){$('notice').textContent=s;}function tab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));}
async function api(path,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw new Error(v.error?.message||'Request failed');return v;}
async function handle(fn){notice();try{await fn();}catch(e){notice(e.message);}}
function download(name,data,raw=false){const url=URL.createObjectURL(new Blob([raw?data:JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function form(){
 $('problem').value=definition.problem;$('notes').value=definition.notes;
 $('site-inputs').innerHTML=definition.sites.map((s,i)=>`<tr><td>${esc(s.name)}</td>${['power_kw','max_rack_kw','racks','liquid_racks','pue'].map(k=>`<td><input type="number" data-site="${i}" data-key="${k}" aria-label="${esc(s.name)} ${k}" value="${s[k]}" min="${k==='pue'?1:0}" step="${k==='pue'?'.01':1}"></td>`).join('')}</tr>`).join('');
 $('provider-inputs').innerHTML=definition.providers.map((p,i)=>`<tr><td>${esc(p.name)}</td><td><input type="checkbox" data-provider="${i}" data-key="enabled" aria-label="${esc(p.name)} enabled" ${p.enabled?'checked':''}></td>${['power_kw','lead_days'].map(k=>`<td><input type="number" data-provider="${i}" data-key="${k}" aria-label="${esc(p.name)} ${k}" value="${p[k]}" min="0" step="any"></td>`).join('')}</tr>`).join('');
 $('parameters').innerHTML=[...new Set(catalog.parameters.map(p=>p.group))].map(g=>`<details class="parameter-group" ${g==='Delivery'?'open':''}><summary>${esc(g)}<small>${g==='Run'?'Settings':'Assumed inputs'}</small></summary><div class="parameter-grid">${catalog.parameters.filter(p=>p.group===g).map(p=>`<div><label for="p-${p.id}">${esc(p.label)}<span class="unit">${esc(p.unit)}</span></label><input type="number" data-parameter="${p.id}" id="p-${p.id}" value="${definition.parameters[p.id]}" min="${p.minimum}" max="${p.maximum}" step="${['days','seed','qualifiers','designers','installers','upgrade','alternatives'].includes(p.id)?1:'any'}"><div class="small">${esc(p.description)}</div></div>`).join('')}</div></details>`).join('');
 $('definition').querySelectorAll('input,select,textarea').forEach(e=>e.disabled=!!session);$('import-definition').disabled=!!session;document.querySelectorAll('[data-preset]').forEach(e=>e.disabled=!!session);
}
function read(){const c=structuredClone(definition);c.problem=$('problem').value;c.notes=$('notes').value;document.querySelectorAll('[data-parameter]').forEach(e=>c.parameters[e.dataset.parameter]=e.value===''?NaN:Number(e.value));for(const [selector,key,array]of[['[data-site]','site','sites'],['[data-provider]','provider','providers']])document.querySelectorAll(selector).forEach(e=>c[array][Number(e.dataset[key])][e.dataset.key]=e.type==='checkbox'?e.checked:e.value===''?NaN:Number(e.value));if(Object.values(c.parameters).some(x=>!Number.isFinite(x)))throw new Error('Complete the numeric assumptions.');return c;}
function controls(){$('play').textContent=playing?'Ⅱ Pause':'▶ Play';$('play').disabled=(pending&&!playing)||!!session&&session.status!=='paused';$('step').disabled=pending||playing||!!session&&session.status!=='paused';$('reset').disabled=pending;$('export-run').disabled=!session||pending;$('status').textContent=pending?'Computing native events…':session?session.status==='completed'?'Horizon reached':playing?'Running':session.status==='paused'?'Paused · no future state computed':session.status:'No outcomes computed';}
function metrics(m={}){$('kpis').innerHTML=[['Active customers',num(m.active)],['Lost opportunities',num(m.lost)],['Recognized revenue',money(m.revenue)],['Operating contribution',money(m.contribution)]].map(([k,v])=>`<div class="kpi"><span>${k}</span><b>${v}</b></div>`).join('');}
function pipeline(f){const c=f?.counts;const stages=[['Qualify',c?c[0]+c[1]:null,c?`${c[0]} queued · ${c[1]} working`:'—'],['Design',c?c[2]+c[3]:null,c?`${c[2]} queued · ${c[3]} working`:'—'],['Allocate',c?c[4]+c[5]:null,c?`${c[4]} capacity · ${c[5]} equipment`:'—'],['Install',c?c[6]+c[7]:null,c?`${c[6]} queued · ${c[7]} working`:'—'],['Activate',c?.[8],f?`${num(f.metrics.active_kw)} IT kW active`:'—']];$('pipeline').innerHTML=stages.map(([k,v,n],i)=>`<button class="stage ${v>5&&i<4?'pressure':''}" data-stage="${i}"><strong>${i+1}. ${k}</strong><b>${num(v)}</b><span>${n}</span></button>`).join('');if(f){$('pipeline-note').textContent=`${f.metrics.opportunities} opportunities · ${f.metrics.pipeline} in process · ${f.metrics.active} active · ${f.metrics.lost} lost. Select a customer below.`;$('customer-cloud').className='customer-cloud';$('customer-cloud').innerHTML=f.customers.map(a=>`<button class="customer ${group(a.state)} ${selected?.type==='customer'&&selected.id===a.id?'selected':''}" data-customer="${a.id}" aria-label="Customer ${a.id+1}, ${types[a.type]}, ${stateNames[a.state]}" title="Customer ${a.id+1} · ${esc(a.reason)}">${a.id+1}</button>`).join('')||'<div class="small">No opportunities have arrived yet.</div>';}}
function sites(f){$('sites').innerHTML=definition.sites.map((d,i)=>{const s=f?.sites[i];return `<button class="site" data-inspect-site="${i}"><h3>${esc(d.name)}</h3><div class="capacity"><b>${num(s?.reserved_kw)}</b><span>/ ${num(s?.power_kw??d.power_kw)} IT kW</span></div><div class="bar"><span class="reserved" style="width:${s&&s.power_kw?Math.min(100,100*s.reserved_kw/s.power_kw):0}%"></span><span class="active-power" style="width:${s&&s.power_kw?Math.min(100,100*s.active_kw/s.power_kw):0}%"></span></div><small>Reserved ↑ · green = active capacity</small><small>Racks: ${num(s?.used_racks)} / ${num(s?.racks??d.racks)}</small><small>Liquid-capable: ${num(s?.used_liquid)} / ${num(s?.liquid_racks??d.liquid_racks)}</small><small>Actual IT draw: ${num(s?.it_draw_kw)} kW</small></button>`;}).join('');}
function chart(id,keys,colors,fmt){if(frames.length<2)return;const maxX=Math.max(frames.at(-1).time,1),vals=frames.flatMap(f=>keys.map(k=>f.metrics[k])),lo=Math.min(0,...vals),hi=Math.max(1,...vals);$(id).className='chart';$(id).innerHTML=`<svg viewBox="0 0 400 140" role="img" aria-label="Computed ${keys.join(' and ')}"><text x="0" y="12" font-size="9" fill="#7b8882">${esc(fmt(hi))}</text><line x1="40" y1="116" x2="390" y2="116" stroke="#dfe4de"/>${keys.map((k,i)=>`<polyline fill="none" stroke="${colors[i]}" stroke-width="2" points="${frames.map(f=>`${40+350*f.time/maxX},${116-100*(f.metrics[k]-lo)/(hi-lo)}`).join(' ')}"/>`).join('')}<text x="40" y="136" font-size="9" fill="#7b8882">Start</text><text x="335" y="136" font-size="9" fill="#7b8882">Day ${num(maxX,1)}</text></svg><div class="chart-key">${keys.map((k,i)=>`<span style="color:${colors[i]}">● ${k==='cost'?'Operating expense':k}</span>`).join(' · ')}</div>`;}
function inspect(){if(!session||!selected)return;const f=session.frame;let rows=[],reason='';if(selected.type==='customer'){const a=f.customers.find(x=>x.id===selected.id);$('inspect-title').textContent=`Customer ${a.id+1}`;reason=a.reason;rows=[['Type',types[a.type]],['Stage',stateNames[a.state]],['Deployment',a.blocks+' rack blocks'],['Cooling',a.liquid?'Liquid required':'Air-compatible'],['Preferred site',definition.sites[a.preferred_site].name],['Site flexibility',a.site_lock?'Preferred site only':'Alternative allowed'],['Preferred partner',definition.providers[a.preferred_provider].name],['Provider flexibility',a.provider_lock?'Preferred partner only':'Modeled substitutes allowed'],['Assigned site',a.site<0?'Unassigned':definition.sites[a.site].name],['Assigned partner',a.provider<0?'Unassigned':definition.providers[a.provider].name],['Reserved IT power',num(a.kw)+' kW'],['Monthly budget',money(a.budget)],['Decision deadline','Day '+num(a.deadline,1)],['Age',num(f.time-a.born,1)+' days'],['Revenue earned',money(a.revenue)]];}else if(selected.type==='site'){const s=f.sites[selected.id];$('inspect-title').textContent=s.name;rows=[['IT capacity',num(s.power_kw)+' kW'],['Reserved',num(s.reserved_kw)+' kW'],['Activated',num(s.active_kw)+' kW'],['Actual IT draw',num(s.it_draw_kw)+' kW'],['Maximum rack density',num(s.max_rack_kw)+' kW'],['PUE',s.pue],['Rack positions',`${s.used_racks} / ${s.racks}`],['Liquid-capable',`${s.used_liquid} / ${s.liquid_racks}`]];reason='Reservations include equipment and installation stages. Revenue begins on activation.';}else{$('inspect-title').textContent=['Qualification','Solution design','Capacity & equipment','Installation','Activation'][selected.id];const i=selected.id;rows=i===0?[['Queued',f.counts[0]],['Working',f.busy[0]],['Lanes',definition.parameters.qualifiers]]:i===1?[['Queued',f.counts[2]],['Working',f.busy[1]],['Lanes',definition.parameters.designers]]:i===2?[['Awaiting capacity',f.counts[4]],['Awaiting equipment',f.counts[5]]]:i===3?[['Queued',f.counts[6]],['Working',f.busy[2]],['Lanes',definition.parameters.installers]]:[['Active',f.metrics.active],['Mean activation time',num(f.metrics.activation_days,1)+' days']];reason=i===2?'Inspect individual customers for the constraints preventing allocation.':'Shared resources and customer deadlines determine progress.';}$('inspector').innerHTML=`<div class="reason">${esc(reason)}</div>`+rows.map(([k,v])=>`<div class="inspector-row"><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('');}
function render(v){session=v;const f=v.frame;if(frames.at(-1)?.time!==f.time)frames.push(f);$('clock').textContent=`Day ${num(f.time,2)} / ${definition.parameters.days}`;$('identity').textContent=`Definition ${v.config_sha256.slice(0,12)} · seed ${definition.parameters.seed}`;metrics(f.metrics);pipeline(f);sites(f);chart('customer-chart',['active','lost'],['#39816b','#bd7f65'],num);chart('money-chart',['revenue','cost'],['#39816b','#b58c53'],money);$('checks').innerHTML=f.checks.map(c=>`<details class="native-check"><summary><span>${esc(c.name)}</span><b class="${c.passed?'pass':'fail'}">${c.passed?'PASS':'FAIL'}</b></summary><div>Actual: ${num(c.actual,5)}<br>Expected: ${num(c.expected,5)}<br>Gap: ${Math.abs(c.actual-c.expected).toExponential(2)}<br>Tolerance: ${c.tolerance.toExponential(2)}</div></details>`).join('');$('events').innerHTML=[...f.events].reverse().slice(0,15).map(e=>`<div class="event"><time>Day ${num(e.time,2)}${e.customer<0?'':` · Customer ${e.customer+1}`}</time>${esc(e.text)}</div>`).join('')||'No events yet.';inspect();if(v.status!=='paused')playing=false;controls();}
function blank(){frames=[];selected=null;evidence=null;$('clock').textContent='Not started';$('identity').textContent='Definition and seed captured when execution starts.';$('customer-cloud').className='empty';$('customer-cloud').textContent='Customer agents appear when opportunities arrive.';$('pipeline-note').textContent='Nothing has been simulated yet.';$('checks').textContent='No checks executed yet.';$('events').textContent='No events executed yet.';$('inspect-title').textContent='Why is it waiting?';$('inspector').textContent='Select a customer, stage or site after running.';['money-chart','customer-chart'].forEach(id=>{$(id).className='chart empty';$(id).textContent='Run to compute a trajectory';});$('evidence-results').textContent='No operational observations supplied.';$('export-evidence').disabled=true;metrics();pipeline();sites();controls();}
async function initialize(){if(session)return;definition=read();render(await api('/api/sessions',definition));form();}
async function advance(){if(pending)return;pending=true;controls();try{await initialize();if(session.status==='paused')render(await api(`/api/sessions/${session.id}/step`,{expected_revision:session.revision,days:Number($('advance').value)}));}catch(e){playing=false;notice(e.message);}finally{pending=false;controls();}if(playing&&session?.status==='paused')timer=setTimeout(advance,Number($('pace').value));}
function pause(){playing=false;clearTimeout(timer);controls();}
async function reset(){pause();if(pending)return;if(session)await api(`/api/sessions/${session.id}/stop`,{});session=null;form();blank();}
function results(){const e=experiment;if(!e)return;$('experiment-status').textContent=`${e.status} · ${e.finished}/${e.total} runs · ${e.config.parameters.days} days · seeds ${e.config.parameters.seed}–${e.config.parameters.seed+e.replications-1}${e.error?' · '+e.error:''}`;$('progress').max=e.total;$('progress').value=e.finished;$('run-experiment').disabled=['queued','running','cancelling'].includes(e.status);$('cancel-experiment').disabled=!['queued','running'].includes(e.status);$('export-experiment').disabled=!e.results.length;if(!e.results.length)return;
 const summary=(rows,k,fmt)=>{const vs=rows.map(r=>r.metrics[k]).filter(v=>v!=null);return vs.length?`${fmt(vs.reduce((a,b)=>a+b,0)/vs.length)}<span class="range">${fmt(Math.min(...vs))} – ${fmt(Math.max(...vs))}</span>`:'—';};
 $('results').className='table-scroll';$('results').innerHTML=`<div class="experiment-note">Means and observed min–max across finished seeds. Contribution excludes depreciation and investment; investment is shown separately. Paired changes compare matching seeds with the first listed value. Results retain the original definition.</div><table><thead><tr><th>Scenario / runs</th><th>Activated</th><th>Lost</th><th>Mean activation days</th><th>Revenue</th><th>Contribution</th><th>Paired contribution change</th><th>Investment</th></tr></thead><tbody>${e.values.map(value=>{const rows=e.results.filter(r=>r.value===value),paired=rows.map(r=>{const b=e.results.find(x=>x.value===e.values[0]&&x.seed===r.seed);return b?r.metrics.contribution-b.metrics.contribution:null;}).filter(x=>x!==null);return `<tr><td>${esc(e.variable==='strategy'?catalog.presets[value].label:value)}<span class="range">${rows.length}/${e.replications} runs</span></td><td>${summary(rows,'active',v=>num(v,1))}</td><td>${summary(rows,'lost',v=>num(v,1))}</td><td>${summary(rows,'activation_days',v=>num(v,1))}</td><td>${summary(rows,'revenue',money)}</td><td>${summary(rows,'contribution',money)}</td><td>${paired.length?money(paired.reduce((a,b)=>a+b,0)/paired.length):'—'}</td><td>${summary(rows,'capex',money)}</td></tr>`;}).join('')}</tbody></table>`;
}
async function poll(){try{experiment=await api(`/api/experiments/${experiment.id}`);results();if(['queued','running','cancelling'].includes(experiment.status))setTimeout(poll,700);}catch(e){notice(e.message);$('run-experiment').disabled=false;}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('edit-assumptions').onclick=()=>tab('definition');$('play').onclick=()=>handle(async()=>{if(playing){pause();return;}playing=true;await advance();});$('step').onclick=()=>handle(advance);$('reset').onclick=()=>handle(reset);
$('presets').onclick=e=>handle(async()=>{const b=e.target.closest('[data-preset]');if(!b||session)return;definition=read();const preset=catalog.presets[Number(b.dataset.preset)];const changed=new Set(catalog.presets.flatMap(p=>Object.keys(p.changes)));for(const k of changed)definition.parameters[k]=catalog.default.parameters[k];Object.assign(definition.parameters,preset.changes);form();sites();document.querySelectorAll('[data-preset]').forEach(x=>x.classList.toggle('selected',x===b));$('preset-note').textContent=preset.description+' Other assumptions are retained.';});
$('customer-cloud').onclick=e=>{const b=e.target.closest('[data-customer]');if(b){selected={type:'customer',id:Number(b.dataset.customer)};inspect();}};$('sites').onclick=e=>{const b=e.target.closest('[data-inspect-site]');if(b&&session){selected={type:'site',id:Number(b.dataset.inspectSite)};inspect();}};$('pipeline').onclick=e=>{const b=e.target.closest('[data-stage]');if(b&&session){selected={type:'stage',id:Number(b.dataset.stage)};inspect();}};
$('definition').addEventListener('input',()=>{document.querySelectorAll('[data-preset]').forEach(x=>x.classList.remove('selected'));$('preset-note').textContent='Custom definition · edit assumptions before running.';});
$('export-definition').onclick=()=>handle(async()=>download('equinix-ai-definition.json',read()));$('import-definition').onclick=()=>$('definition-file').click();$('definition-file').onchange=e=>handle(async()=>{const f=e.target.files[0];if(!f)return;if(f.size>100000)throw new Error('Definition must be smaller than 100 KB.');const v=await api('/api/validate',JSON.parse(await f.text()));definition=v.definition;form();blank();e.target.value='';notice('Definition imported and validated. No simulation executed.');});
$('export-run').onclick=()=>handle(async()=>{const r=await fetch(`/api/sessions/${session.id}/record`);if(!r.ok)throw new Error('Export failed');download('equinix-ai-run.json',await r.text(),true);});
$('variable').onchange=()=>{$('values').value=({strategy:'0, 1, 2, 3, 4, 5',arrivals:'0.4, 0.8, 1.6',designers:'2, 3, 4',installers:'1, 2, 3',design_saving:'0, 0.2, 0.4',colo_price:'200, 250, 300',patience:'30, 45, 60'})[$('variable').value];};
$('run-experiment').onclick=()=>handle(async()=>{const raw=$('values').value.split(',');if(raw.some(x=>!x.trim()))throw new Error('Every value must be numeric.');experiment=await api('/api/experiments',{config:read(),variable:$('variable').value,values:raw.map(Number),replications:Number($('replications').value)});$('results').textContent='Waiting for the first native run…';results();poll();});$('cancel-experiment').onclick=()=>handle(async()=>{experiment=await api(`/api/experiments/${experiment.id}/cancel`,{});results();});$('export-experiment').onclick=()=>download('equinix-ai-experiment.json',experiment);
$('template').onclick=()=>download('equinix-ai-observations.json',{source:'Replace with dataset name, vintage and start-date alignment',kind:'observed',rows:[{time:session?.frame.time??30,metric:'active',unit:'customer',actual:null,tolerance:1},{time:session?.frame.time??30,metric:'revenue',unit:'USD',actual:null,tolerance:1000}]});$('upload-evidence').onclick=()=>handle(async()=>{if(!session)throw new Error('Run the model before attaching observations.');$('evidence-file').click();});$('evidence-file').onchange=e=>handle(async()=>{const f=e.target.files[0];if(!f)return;if(f.size>1000000)throw new Error('Observation file exceeds 1 MB.');evidence=await api(`/api/sessions/${session.id}/evidence`,JSON.parse(await f.text()));$('evidence-results').className='table-scroll';$('evidence-results').innerHTML=`<p class="${evidence.passed?'pass':'fail'}">${evidence.passed?'Within supplied tolerances':'Outside supplied tolerances'} · ${esc(evidence.kind)} · ${esc(evidence.source)}</p><table><thead><tr><th>Day / metric</th><th>Observed</th><th>Modeled</th><th>Error / tolerance</th><th>Result</th></tr></thead><tbody>${evidence.rows.map(r=>`<tr><td>${r.time} / ${esc(r.metric)}</td><td>${num(r.actual,3)}</td><td>${num(r.predicted,3)}</td><td>${num(r.error,3)} / ${r.tolerance}</td><td>${r.passed?'PASS':'FAIL'}</td></tr>`).join('')}</tbody></table>`;$('export-evidence').disabled=false;e.target.value='';});$('export-evidence').onclick=()=>download('equinix-ai-evidence.json',evidence);
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('pagehide',()=>{if(session)fetch(`/api/sessions/${session.id}/stop`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}',keepalive:true});});
await handle(async()=>{catalog=await api('/api/catalog');definition=structuredClone(catalog.default);$('presets').innerHTML=catalog.presets.map((p,i)=>`<button class="preset ${i===0?'selected':''}" data-preset="${i}">${esc(p.label)}</button>`).join('');form();blank();$('methods').innerHTML=catalog.methods.map(m=>`<div class="method"><h3><span>${m.method}</span>${esc(m.name)}</h3><code>${esc(m.implementation)}</code><p>${esc(m.rule)}</p></div>`).join('');$('limits').innerHTML=catalog.limitations.map(l=>`<li>${esc(l)}</li>`).join('');$('sources').innerHTML=catalog.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noreferrer">${esc(s.title)} ↗</a>`).join('');});
await handle(async()=>{const r=await api('/api/verification');$('verification').innerHTML=!r.available?'No test receipt recorded yet.':`<p class="${r.passed&&r.sources_current?'pass':'fail'}">${r.passed?'Recorded checks passed':'Check failures'} · ${r.sources_current?'sources unchanged':'source edits since receipt'}</p><p>${esc(r.scope)}</p>`;});
