import {escapeHTML as esc,sameControls} from '/ui-model.mjs';
const $=id=>document.getElementById(id);
const labels={revenue:'Revenue',ebitda:'EBITDA',cash_flow:'Operating cash',headcount:'Ending workforce',utilization:'Utilization'};
const fmt=(v,key)=>v==null?'—':key==='utilization'?`${(v*100).toFixed(1)}%`:key==='headcount'?`${v.toFixed(1)} FTE`:`$${(v/1e6).toFixed(2)}M`;
const numeric=v=>v==null?'Undefined':v.toLocaleString('en-US',{maximumSignificantDigits:6});
const short=s=>s?`${s.slice(0,12)}…`:'Not recorded';
const json=v=>`<pre>${esc(JSON.stringify(v,null,2))}</pre>`;
function download(name,value){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function request(path,body){const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const result=await response.json();if(!response.ok)throw Error(result.error?.message??'Request failed');return result;}
function table(headers,rows){return `<div class="validation-table"><table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function lineChart(rows,first,second,label,options={}){
  if(!rows.length)return '';
  const width=800,height=235,pad=48;const values=rows.flatMap(r=>[first(r),second(r)]).filter(v=>v!=null);
  const min=Math.min(0,...values),max=Math.max(1,...values),x=i=>pad+i*(width-2*pad)/Math.max(1,rows.length-1),y=v=>height-pad-(v-min)/(max-min)*(height-2*pad);
  const path=fn=>rows.map((r,i)=>fn(r)==null?'':`${i===0?'M':'L'}${x(i).toFixed(1)},${y(fn(r)).toFixed(1)}`).join(' ');
  const marker=options.index!=null?`<line x1="${x(options.index)}" x2="${x(options.index)}" y1="${pad}" y2="${height-pad}" stroke="#167c71" stroke-dasharray="3 3"/>`:'';
  const split=options.cutoff!=null?rows.findIndex(r=>r.month>options.cutoff):-1;
  const shade=split>=0?`<rect x="${x(split)}" y="${pad-15}" width="${width-pad-x(split)}" height="${height-2*pad+15}" fill="#f3eadb" opacity=".7"/><text x="${x(split)+6}" y="${pad-2}">Holdout</text>`:'';
  return `<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(label)}">${shade}${marker}<line x1="${pad}" y1="${y(0)}" x2="${width-pad}" y2="${y(0)}" stroke="#dbe1db"/><text x="4" y="${pad}">${esc(numeric(max))}</text><text x="4" y="${height-pad}">${esc(numeric(min))}</text><path d="${path(first)}" fill="none" stroke="#89968e" stroke-width="2" stroke-dasharray="5 4"/><path d="${path(second)}" fill="none" stroke="#167c71" stroke-width="3"/><text x="${pad}" y="${height-12}">Month ${rows[0].end??rows[0].month}</text><text x="${width-pad}" y="${height-12}" text-anchor="end">Month ${rows.at(-1).end??rows.at(-1).month}</text></svg>`;
}

export function initValidation(getDisplay){
 let catalog=null,evidence=null,playback=null,history=null,timer=null,index=0,version=0,tab='evidence';
 const selection=()=>$('validation-run').value;
 const message=text=>{$('validation-status').textContent=text;};
 const stop=()=>{clearInterval(timer);timer=null;$('validation-play').textContent='▶ Play';};
 const setTab=name=>{tab=name;for(const el of document.querySelectorAll('[data-validation-tab]')){el.classList.toggle('active',el.dataset.validationTab===name);el.setAttribute('aria-selected',String(el.dataset.validationTab===name));}for(const el of document.querySelectorAll('[data-validation-panel]'))el.hidden=el.dataset.validationPanel!==name;stop();};
 $('validation').innerHTML=`
 <div class="panel validation-intro"><div class="panel-heading"><div><div class="eyebrow">EVIDENCE, NOT ASSURANCE</div><h2>See what supports the result.</h2></div><button id="evidence-export" class="subtle-button" disabled>Export evidence ↓</button></div><p class="muted">Inspect the mathematical model, its execution and its checks. Technical verification and historical accuracy are separate questions. The run selector below controls this workspace; sidebar edits apply to a future execution.</p><div class="validation-controls"><label>Inspect run<select id="validation-run"><option>Loading run records…</option></select></label><button id="validation-refresh" class="subtle-button">Verify saved evidence</button></div><p id="validation-status" role="status">Loading model and run records…</p></div>
 <div class="validation-badges" id="validation-badges"></div>
 <nav class="validation-tabs" aria-label="Validation sections"><button data-validation-tab="evidence" class="active">Checks & evidence</button><button data-validation-tab="model">Model & runs</button><button data-validation-tab="playback">Playback</button><button data-validation-tab="history">Historical fit</button></nav>
 <section class="panel" data-validation-panel="evidence"><h2>Checks you can inspect</h2><div id="validation-checks"></div><details><summary>Declared native rules and tolerances</summary><p class="muted">These are the exact model assertions. Live runs retain a successful require-check execution, but no per-rule residual receipt. The independently recomputed residuals above have narrower scope.</p><div id="validation-native"></div></details><details><summary>Earlier synthetic pilot evidence</summary><div id="validation-pilot"></div></details><details><summary>Execution settings, commands and identities</summary><div id="validation-execution"></div></details><details><summary>Project test commands and recorded output</summary><div id="validation-project-checks"></div></details><details><summary>AI author and reviewer provenance</summary><div id="validation-agent"></div></details></section>
 <section class="panel" data-validation-panel="model" hidden><div class="eyebrow">CURRENTLY REGISTERED MATHEMATICAL MODEL</div><h2 id="validation-model-name"></h2><div id="validation-model-summary"></div><div class="note">System dynamics is used for this T&R monthly transition model. The platform’s discrete-event and agent-based engines are not used by this model. AI savings are scenario assumptions; an AI model is not generating the numerical trajectory.</div><h3>Find an equation or stock</h3><label for="equation-search">Search native IDs, units or expressions</label><input id="equation-search" type="search" placeholder="Try revenue, backlog, fte or cash"><p id="equation-count" class="muted"></p><div id="equation-list"></div><details><summary>All parameters: effective defaults, units and sources</summary><div id="validation-parameters"></div></details><details><summary>Data bindings and metric definitions</summary><div id="validation-bindings"></div></details><h3>Recorded executions</h3><p class="muted">Each row is a recorded engine job, including failed and cancelled attempts. Select a completed run above to inspect its own immutable model version and scenarios.</p><div id="validation-runs"></div></section>
 <section class="panel" data-validation-panel="playback" hidden><div class="eyebrow">FOLLOW THE RECORDED TRAJECTORY</div><h2>A month at a time.</h2><p class="muted">These are saved numerical observations from the selected run. No new simulation is executed by playback. Replication 0.</p><div class="validation-controls"><label>Observation interval<select id="validation-interval"><option value="1">Monthly</option><option value="3">Quarterly</option><option value="12">Annual</option></select></label><label>Playback speed<select id="validation-speed"><option value="1600">0.5×</option><option value="800" selected>1×</option><option value="400">2×</option><option value="200">4×</option></select></label><button id="validation-play" class="subtle-button" disabled>▶ Play</button></div><div class="validation-scrub"><input id="validation-scrub" type="range" min="0" max="59" value="0" aria-label="Recorded period"><strong id="validation-period">Loading…</strong></div><div id="validation-frame"></div><div class="chart-legend"><span><i class="baseline-line"></i>Scenario 0</span><span><i class="candidate-line"></i>Scenario 1</span><span>Period revenue · USD</span></div><div id="validation-trajectory"></div><details open><summary>Simulation timestep is a different setting</summary><label>Integration step<select aria-label="Simulation timestep" disabled><option>1 month · required by this model</option></select></label><div id="validation-timestep"></div></details></section>
 <section class="panel" data-validation-panel="history" hidden><div class="eyebrow">OBSERVED VERSUS SIMULATED</div><h2>Test against a historical period.</h2><p class="muted">Import monthly actuals, identify the calibration cutoff, and evaluate the later period against a frozen run. This tool evaluates supplied values; it does not fit parameters or prove that holdout data was unseen.</p><div class="validation-controls"><label>Simulated scenario<select id="history-scenario"></select></label><label>Import JSON<input id="history-file" type="file" accept="application/json,.json"></label><button id="history-template" class="subtle-button">Download data template</button><button id="history-demo" class="subtle-button">Load synthetic demonstration</button></div><label for="history-input">Historical dataset, source and acceptance thresholds</label><textarea id="history-input" rows="8" spellcheck="false" placeholder="Import a JSON dataset or load the clearly labeled synthetic demonstration."></textarea><p class="footnote">Revenue, EBITDA and cash: USD earned/flow during the month. Headcount: ending expected FTE (person). Utilization: fraction of billable-role paid hours. Month 1 maps to start_month. Missing values and month gaps are rejected. Thresholds are supplied with the evaluation, not preregistered.</p><div class="validation-controls"><button id="history-evaluate" class="primary" disabled>Evaluate historical fit</button><button id="history-restore" class="subtle-button">Load latest saved evaluation</button><button id="history-export" class="subtle-button" disabled>Export evaluation ↓</button></div><p id="history-status" role="status">No actual practice history has been supplied.</p><div id="history-report"></div></section>`;
 for(const b of document.querySelectorAll('[data-validation-tab]'))b.addEventListener('click',()=>setTab(b.dataset.validationTab));
 function modelView(){
  const m=catalog.model;$('validation-model-name').textContent=m.name;
  $('validation-model-summary').innerHTML=`<p>${m.components.length} native components · ${m.parameters.length} parameters · ${m.checks.length} assertions · ${m.time.horizon} months · Euler, step ${m.time.dt} month</p><p class="footnote">Registered version <code>${esc(m.description.model_version)}</code>. Selected-run settings are shown separately in Checks & evidence.</p>`;
  $('validation-parameters').innerHTML=table(['Parameter','Effective default','Unit','Status / source'],m.parameters.map(p=>[esc(p.id),numeric(p.effective_value),esc(p.unit),esc(p.status+' · '+p.source)]));
  $('validation-bindings').innerHTML=json({bindings:m.data,metrics:m.description.metrics,input_sha256:m.description.input_sha256});
  $('validation-runs').innerHTML=table(['Run / created','Status','Model version','Scenarios / settings'],catalog.runs.map(r=>[`${esc(short(r.id))}<br>${esc(new Date(r.created_at*1000).toLocaleString())}`,esc(r.status),esc(short(r.model_version)),`${r.effective_parameters.length} scenarios · seed ${r.request.experiment.seed} · ${r.request.threads} threads<br>${esc(r.effective_parameters.map(s=>`ID ${s.id}: AI ${Math.round(s.parameters.ai*100)}%, demand ${s.parameters.demand_scale}×`).join('; '))}`]));
  $('validation-agent').innerHTML=`<p>${esc(catalog.agent_provenance.explanation)}</p><strong>AI model identity: not recorded</strong>`;
  const checks=catalog.project_checks;$('validation-project-checks').innerHTML=checks?`<p>Recorded source files match this checkout: <strong>${checks.current_sources_match?'yes':'NO — evidence is stale'}</strong>. ${esc(checks.scope)}</p>${json(checks)}`:'No executable project-check receipt has been recorded.';
  const p=catalog.pilot;
  $('validation-pilot').innerHTML=`<p>${esc(p.scope)}</p><p>Receipt matches checked-in preview: <strong>${p.receipt_matches_preview?'yes':'no'}</strong>. Model/data match current registration: <strong>${p.inputs_match_current?'yes':'no'}</strong>.</p><p>Hashes establish identity and detect changes; they are not independent review or real-world validation.</p>${json(p)}`;
  $('validation-timestep').innerHTML=`<p>${esc(m.timestep.reason)}</p><div class="note">Timestep convergence is not established. This project cannot offer a valid finer-step run without revising the model. Observation interval and playback speed can be changed safely.</div>`;
  equations();
 }
 function equations(){const text=$('equation-search').value.toLowerCase();const items=catalog.model.components.filter(c=>JSON.stringify(c).toLowerCase().includes(text));$('equation-count').textContent=`${items.length} matches · showing ${Math.min(30,items.length)}. Refine the search or export the complete model evidence.`;$('equation-list').innerHTML=table(['Component','Kind / unit','Native definition'],items.slice(0,30).map(c=>[esc(c.id),`${esc(c.kind)}<br>${esc(c.unit)}`,`<code>${esc(c.expr??`initial value = ${c.init}`)}</code>`]));}
 $('equation-search').addEventListener('input',equations);
 function badges(){const reconciled=evidence?.reconciliations.every(r=>r.verdict==='pass');$('validation-badges').innerHTML=[['Artifact integrity',evidence?'Checked now':'Not checked','Saved run artifacts checked'],['Accounting checks',evidence?(reconciled?'Passed':'Failed'):'Not checked','Residuals shown below'],['Historical accuracy','Not established','Evaluate actual practice observations'],['Numerical step','Monthly model','Finer-step convergence unavailable']].map(([a,b,c])=>`<article><span>${a}</span><strong>${b}</strong><small>${c}</small></article>`).join('');}
 async function loadRun(){
  stop();const ticket=++version;const key=selection();evidence=null;playback=null;history=null;badges();$('validation-checks').textContent='Loading selected-run evidence…';$('validation-native').textContent='';$('validation-execution').textContent='';$('history-report').innerHTML='';$('history-status').textContent='No evaluation for this selected run.';$('history-export').disabled=true;$('history-evaluate').disabled=true;$('evidence-export').disabled=true;$('validation-play').disabled=true;$('validation-frame').textContent='Loading recorded periods…';$('validation-trajectory').innerHTML='';
  if(!key){message('Run a comparison to create live evidence. The model and earlier pilot receipts remain inspectable.');return;}
  message('Checking immutable saved artifacts and calculating accounting residuals…');
  try{const data=await request('/project/evidence?run_id='+encodeURIComponent(key));if(ticket!==version)return;evidence=data;badges();
   $('validation-checks').innerHTML=`<p>Run <code>${esc(key)}</code> · model <code>${esc(short(data.job.model_version))}</code>. Saved-output reconciliation across every scenario, replication and recorded time.</p>`+table(['Scenario','AI savings','Pipeline multiplier','Hiring policy'],data.job.effective_parameters.map(s=>[s.id,`${Math.round(s.parameters.ai*100)}%`,`${s.parameters.demand_scale}×`,s.parameters.policy_hold?'Replace departures':s.parameters.policy_responsive?'Responsive':'Freeze']))+table(['Identity','Samples / failures','Worst recorded comparison','Tolerance / verdict'],data.reconciliations.map(r=>[`${esc(r.id)}<br><code>${esc(r.expression)}</code>`,`${r.samples} / ${r.failures}`,r.worst?`Expected ${numeric(r.worst.expected)}<br>Observed ${numeric(r.worst.observed)}<br>Gap ${numeric(r.worst.absolute_gap)} · scenario ${r.worst.scenario}, month ${r.worst.time}`:'No observations',`${r.worst?numeric(r.worst.tolerance):'—'}<br><strong>${esc(r.verdict)}</strong>`]));
   $('validation-native').innerHTML=table(['Rule','Expression','Tolerance','Execution evidence'],data.checks.map(c=>[esc(c.id),`<code>${esc(c.expr)}</code>`,`${c.absolute_tolerance} absolute<br>${c.relative_tolerance} relative`,esc(c.status.replaceAll('_',' '))]));
   $('validation-execution').innerHTML=json(data);
   $('history-scenario').innerHTML=data.job.effective_parameters.map(s=>`<option value="${s.id}">Scenario ${s.id}${s.id===0?' · baseline':s.id===1?' · candidate':''}</option>`).join('');
   $('history-evaluate').disabled=false;$('evidence-export').disabled=false;
   message('Saved artifacts verified. Accounting evidence loaded. Historical accuracy remains unassessed.');await loadPlayback(ticket);
  }catch(e){if(ticket===version){message('Evidence unavailable: '+e.message);$('validation-checks').textContent='No successful verification is claimed for this selection.';}}
 }
 async function loadPlayback(ticket=version){stop();$('validation-play').disabled=true;const key=selection();if(!key)return;const step=$('validation-interval').value;
  try{const data=await request(`/project/playback?run_id=${encodeURIComponent(key)}&step=${step}`);if(ticket!==version||step!==$('validation-interval').value)return;playback=data;index=0;$('validation-scrub').max=String(data.frames.length-1);$('validation-play').disabled=false;frame();}
  catch(e){if(ticket===version)message('Playback unavailable: '+e.message);}
 }
 function frame(){if(!playback)return;$('validation-trajectory').innerHTML=lineChart(playback.frames,r=>r.scenarios.find(s=>s.id===0)?.values.revenue,r=>r.scenarios.find(s=>s.id===1)?.values.revenue,'Recorded period revenue for scenarios zero and one',{index});const f=playback.frames[index];$('validation-scrub').value=index;$('validation-period').textContent=f.end-f.start===1?`Month ${f.end} of 60`:`Months ${f.start+1}–${f.end} of 60`;$('validation-frame').innerHTML=table(['Metric',...f.scenarios.map(s=>`Scenario ${s.id}`)],Object.entries(labels).map(([k,l])=>[l,...f.scenarios.map(s=>fmt(s.values[k],k))]));}
 $('validation-interval').addEventListener('change',()=>loadPlayback());$('validation-speed').addEventListener('change',stop);$('validation-scrub').addEventListener('input',()=>{stop();index=+$('validation-scrub').value;frame();});
 $('validation-play').addEventListener('click',()=>{if(timer){stop();return;}if(!playback)return;if(index===playback.frames.length-1)index=0;frame();$('validation-play').textContent='Ⅱ Pause';timer=setInterval(()=>{if(index>=playback.frames.length-1){stop();return;}index++;frame();},+$('validation-speed').value);});
 $('validation-run').addEventListener('change',()=>loadRun());$('validation-refresh').addEventListener('click',()=>load());
 $('evidence-export').addEventListener('click',()=>download('tr-validation-evidence.json',{recorded_at:new Date().toISOString(),registered_model:catalog.model,selected_run:evidence,earlier_pilot:catalog.pilot,project_checks:catalog.project_checks,agent_provenance:catalog.agent_provenance}));
 function template(){return {label:'Replace with dataset name',source:'Replace with system/export vintage and accounting definitions',kind:'observed',start_month:'2020-01',calibration_through:24,heldout_attestation:false,thresholds:{revenue:{unit:'USD',mae_max:100000},headcount:{unit:'person',mae_max:5}},rows:Array.from({length:36},(_,i)=>({month:i+1,revenue:null,headcount:null}))};}
 $('history-template').addEventListener('click',()=>download('tr-history-template.json',template()));
 function historyDirty(){history=null;$('history-report').innerHTML='';$('history-export').disabled=true;$('history-status').textContent='Dataset or scenario changed. Evaluate to produce a new receipt.';}
 $('history-input').addEventListener('input',historyDirty);$('history-scenario').addEventListener('change',historyDirty);
 $('history-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;historyDirty();try{if(file.size>1000000)throw Error('File must be at most 1 MB');const text=await file.text();JSON.parse(text);$('history-input').value=text;$('history-status').textContent='File loaded locally. Review the dataset and thresholds before evaluating.';}catch(err){$('history-status').textContent=err.message;}});
 $('history-demo').addEventListener('click',async()=>{const key=selection();if(!key)return;const scenario=+$('history-scenario').value;historyDirty();try{const p=await request(`/project/playback?run_id=${encodeURIComponent(key)}&step=1`);if(key!==selection())return;const data=template();data.kind='synthetic';data.label='Synthetic demonstration — simulated values perturbed by 5%';data.source='Generated from this selected run. This is circular workflow test data, not actual practice history.';data.rows=p.frames.slice(0,36).map(f=>({month:f.end,revenue:f.scenarios.find(s=>s.id===scenario).values.revenue*1.05,headcount:f.scenarios.find(s=>s.id===scenario).values.headcount}));$('history-input').value=JSON.stringify(data,null,2);$('history-status').textContent='Synthetic demonstration loaded. The revenue threshold is deliberately tight enough to expose a discrepancy.';}catch(e){$('history-status').textContent=e.message;}});
 $('history-evaluate').addEventListener('click',async()=>{const key=selection(),text=$('history-input').value,scenario=+$('history-scenario').value;historyDirty();$('history-evaluate').disabled=true;$('history-status').textContent='Evaluating supplied observations against the frozen run…';try{const receipt=await request('/project/history',{run_id:key,scenario,dataset:JSON.parse(text)});if(key!==selection()||text!==$('history-input').value||scenario!==+$('history-scenario').value)return;history=receipt;renderHistory();$('history-export').disabled=false;$('history-status').textContent=`Evaluation saved locally · ${short(receipt.receipt_id)}`;}catch(e){$('history-status').textContent='Evaluation rejected: '+e.message;}finally{$('history-evaluate').disabled=!evidence;}});
 function renderHistory(){const h=history;$('history-report').innerHTML=`<div class="note"><strong>${h.kind==='synthetic'?'SYNTHETIC DEMONSTRATION':'OBSERVED DATA · USER SUPPLIED'}</strong><p>${esc(h.interpretation)}</p><p>${esc(h.threshold_policy)} Holdout independence attested: ${h.heldout_attestation?'yes':'no'}.</p></div><h3>${h.holdout_within_threshold?'Holdout errors are within the supplied limits.':'Holdout errors exceed at least one supplied limit.'}</h3><p>Month 1 = ${esc(h.start_month)}. Calibration through month ${h.calibration_through}; later observations evaluated separately. Errors are simulated minus actual.</p>`+table(['Metric / period','N','MAE / limit','RMSE','Bias','WAPE','Within limit'],h.summaries.map(r=>[`${esc(labels[r.metric])}<br>${esc(r.partition)}`,r.n,numeric(r.mae)+' / '+numeric(r.mae_max),numeric(r.rmse),numeric(r.bias),r.wape==null?'Undefined (zero actuals)':(r.wape*100).toFixed(2)+'%',r.within_threshold?'Yes':'No']))+`<label>Compare historical series<select id="history-metric">${Object.keys(h.observations[0].values).map(k=>`<option value="${k}">${esc(labels[k])}</option>`).join('')}</select></label><div class="chart-legend"><span><i class="baseline-line"></i>Supplied actuals</span><span><i class="candidate-line"></i>Simulation</span></div><div id="history-chart"></div><details><summary>Every observation, source and evaluation receipt</summary>${json(h)}</details>`;if('revenue' in h.observations[0].values)$('history-metric').value='revenue';const draw=()=>{const metric=$('history-metric').value;$('history-chart').innerHTML=lineChart(h.observations,r=>r.values[metric].actual,r=>r.values[metric].simulated,'Actual versus simulated '+labels[metric],{cutoff:h.calibration_through});};$('history-metric').addEventListener('change',draw);draw();}
 $('history-restore').addEventListener('click',async()=>{const key=selection();if(!key)return;try{const response=await request('/project/history?run_id='+encodeURIComponent(key));if(key!==selection())return;const latest=response.evaluations[0];if(!latest){$('history-status').textContent='No saved evaluation for this run.';return;}history=latest;$('history-input').value=JSON.stringify(latest.request.dataset,null,2);$('history-scenario').value=latest.scenario;renderHistory();$('history-export').disabled=false;$('history-status').textContent=`Restored verified receipt ${short(latest.receipt_id)} · ${response.evaluations.length} saved evaluation(s) for this run.`;}catch(e){$('history-status').textContent='Saved evaluation unavailable: '+e.message;}});
 $('history-export').addEventListener('click',()=>{if(history)download('tr-historical-evaluation.json',history);});
 async function load(){stop();message('Loading versioned model and run catalog…');const old=selection();try{catalog=await request('/project/validation');const completed=catalog.runs.filter(r=>r.status==='completed');$('validation-run').innerHTML=completed.map(r=>`<option value="${esc(r.id)}">${esc(new Date(r.created_at*1000).toLocaleString())} · ${esc(short(r.id))} · ${r.effective_parameters.length} scenarios</option>`).join('')||'<option value="">Not checkeds</option>';const display=getDisplay();const current=display?.live?display.provenance.run_id:completed.find(r=>r.effective_parameters.some(s=>s.id===1&&sameControls(s.parameters,display?.controls??{})))?.id;const desired=completed.some(r=>r.id===old)?old:current;if(completed.some(r=>r.id===desired))$('validation-run').value=desired;modelView();await loadRun();}catch(e){message('Validation workspace unavailable: '+e.message);}}
 return {open:load,close:stop};
}
