#define EQUINIX_MODEL_TEST
#include "model.cpp"
#include <fstream>
void require(bool b,const char*m){if(!b)throw std::runtime_error(m);}void near(double a,double b,const char*m){if(std::abs(a-b)>1e-6)throw std::runtime_error(m);}
std::unique_ptr<Market> fixture(J c,double deadline=20,bool liquid=false,bool upgrade=false){auto&p=c["parameters"];p["arrivals"]=0;p["qualification_days"]=1;p["design_days"]=1;p["design_saving"]=0;p["installation_days"]=1;p["win_rate"]=1;p["alternatives"]=0;p["qualifiers"]=1;p["designers"]=1;p["installers"]=1;p["overhead_day"]=100;p["team_cost"]=100;p["upgrade"]=upgrade?1:0;p["upgrade_day"]=3;c["providers"][0]["lead_days"]=2;c["providers"][0]["power_kw"]=40;
 auto m=std::make_unique<Market>(c);m->events={};if(upgrade)m->add(3,0,-1);Customer a;a.born=0;a.deadline=deadline;a.budget=100000;a.liquid=liquid;m->customers.spawn(a);m->add(deadline,4,0);m->dispatch();return m;}
int main(int argc,char**argv){try{if(argc!=2)throw std::runtime_error("definition path required");std::ifstream f(argv[1]);J c;f>>c;
 {af::devs::Simulator<int> sim;auto owner=fixture(c);auto*m=owner.get();auto id=sim.add(std::move(owner));sim.inject(4.5,id,0,0);sim.run_until(4.5);near(m->sd.state()[0],0,"revenue before activation");require(m->customers.records()[0].value.state==7,"installation schedule");sim.inject(6,id,0,0);sim.run_until(6);auto frame=m->frame();require(frame["checks_passed"].get<bool>(),"known schedule checks");near(frame["metrics"]["activation_days"].get<double>(),5,"qualification/design/equipment/install hand schedule");near(frame["metrics"]["revenue"].get<double>(),40*c["parameters"]["colo_price"].get<double>()/30,"one-day revenue");double energy=40*c["parameters"]["it_load"].get<double>()*c["sites"][0]["pue"].get<double>()*24;near(m->sd.state()[2],energy,"one-day PUE energy");near(m->sd.state()[1],400*6+energy*c["parameters"]["electricity"].get<double>(),"hand cost ledger");}
 {af::devs::Simulator<int> sim;auto owner=fixture(c,4.5);auto*m=owner.get();auto id=sim.add(std::move(owner));sim.inject(6,id,0,0);sim.run_until(6);require(m->customers.records()[0].value.state==9&&m->busy[2]==0,"deadline cancels installation and releases crew");near(m->sites[0].reserved,0,"deadline releases power");require(m->sites[0].used==0,"deadline releases racks");near(m->sd.state()[0],0,"abandoned customer revenue");require(m->frame()["checks_passed"].get<bool>(),"stale completion changed ownership");}
 {af::devs::Simulator<int> sim;auto owner=fixture(c,20,true,true);auto*m=owner.get();auto id=sim.add(std::move(owner));sim.inject(2.5,id,0,0);sim.run_until(2.5);require(m->customers.records()[0].value.state==4,"liquid cooling must block allocation");sim.inject(7,id,0,0);sim.run_until(7);require(m->customers.records()[0].value.state==8,"upgrade did not unlock customer");near(m->customers.records()[0].value.activated,6,"upgrade event hand schedule");near(m->sd.state()[3],c["parameters"]["upgrade_cost"].get<double>(),"upgrade investment pulse");}
 std::cout<<"Hand schedules passed: activation, delayed revenue, energy/cost, cancellation/release, cooling upgrade\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
