const $=id=>document.getElementById(id), esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,d=0)=>v==null?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:d});
const money=v=>v==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(v);
const percent=v=>v==null?'—':num(v*100,1)+'%';
let catalog,definition,session=null,frames=[],playing=false,pending=false,timer=null,selected=null,experiment=null,evidence=null;
const stateNames=['Off shift','Available / business development','Delivering','AI training','Administration','Support'];
const stateClass=['off','idle','busy','training','admin','admin'],skillNames=['Liquidity','Restructuring','Operations'],stageNames=['Analysis','Plan & implementation','Senior review'];
const experimentChoices=['license_share','ai_saving','training_hours','prospects_day','review_extra','bd_fraction','secondary_skill','win_rate'];
function notice(text=''){ $('notice').textContent=text; }
async function api(path,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok)throw new Error(result.error?.message||'Request failed');return result;}
function download(name,value,raw=false){const blob=new Blob([raw?value:JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function tab(name){document.querySelectorAll('.tab').forEach(el=>el.classList.toggle('active',el.id===name));document.querySelectorAll('nav button').forEach(el=>el.classList.toggle('active',el.dataset.tab===name));}
function form(){
 $('problem').value=definition.problem;$('notes').value=definition.notes;
 $('levels').innerHTML=definition.levels.map((l,i)=>`<tr><td>${esc(l.name)}</td>${['count','rate','salary'].map(k=>`<td><input type="number" data-level="${i}" data-key="${k}" aria-label="${esc(l.name)} ${k}" value="${l[k]}" min="0" step="${k==='count'?1:100}" max="${k==='count'?500:k==='rate'?5000:2000000}"></td>`).join('')}</tr>`).join('');
 $('headcount').textContent=definition.levels.reduce((s,l)=>s+l.count,0);
 const groups=[...new Set(catalog.parameters.map(p=>p.group))];
 $('parameters').innerHTML=groups.map(g=>`<details ${g==='AI & training'?'open':''}><summary>${esc(g)}<span>${catalog.parameters.filter(p=>p.group===g).length} parameters · ${g==='Experiment'?'settings':'assumed'}</span></summary><div class="parameter-grid">${catalog.parameters.filter(p=>p.group===g).map(p=>`<div class="parameter"><label for="p-${p.id}">${esc(p.label)}<span class="unit">${esc(p.unit)}</span></label><input id="p-${p.id}" type="number" data-parameter="${p.id}" value="${definition.parameters[p.id]}" min="${p.minimum}" max="${p.maximum}" step="${['days','seed','bd_lag'].includes(p.id)?1:'any'}"><div class="muted">${esc(p.description)}</div><small>${esc(p.role)} · validate with: ${esc(p.validation)}</small></div>`).join('')}${g==='AI & training'?`<div class="parameter"><label for="training">Training method</label><select id="training"><option value="self-study">Self-study · learning multiplier 0.5</option><option value="workshop">Workshop · learning multiplier 1.0</option><option value="coaching">Coaching · learning multiplier 1.5</option></select><div class="muted">Hypothetical efficacy multipliers. Hold time and cost constant to isolate this assumption.</div></div>`:''}</div></details>`).join('');$('training').value=definition.training;
 $('define').querySelectorAll('input,select,textarea').forEach(el=>el.disabled=!!session);
}
function read(){const result=structuredClone(definition);result.problem=$('problem').value;result.notes=$('notes').value;result.training=$('training').value;document.querySelectorAll('[data-parameter]').forEach(el=>result.parameters[el.dataset.parameter]=el.value===''?NaN:Number(el.value));document.querySelectorAll('[data-level]').forEach(el=>result.levels[Number(el.dataset.level)][el.dataset.key]=el.value===''?NaN:Number(el.value));if(Object.values(result.parameters).some(v=>!Number.isFinite(v))||result.levels.some(l=>['count','rate','salary'].some(k=>!Number.isFinite(l[k]))))throw new Error('Complete every numeric assumption before running.');return result;}
function clock(t){return `Day ${Math.floor(t/24)+1} · ${String(Math.floor(t%24)).padStart(2,'0')}:${String(Math.floor(t*60%60)).padStart(2,'0')}`;}
function controls(){const end=session&&session.status!=='paused';$('play').textContent=playing?'Ⅱ Pause':'▶ Play';$('play').disabled=!!end||pending&&!playing;$('step').disabled=pending||playing||!!end;$('reset').disabled=pending;$('export-run').disabled=!session||pending;$('import-definition').disabled=!!session;$('run-status').textContent=pending?'Computing the next interval…':session?(session.status==='completed'?'Horizon reached':playing?'Running native events':session.status==='paused'?'Paused · future state not computed':session.status):'No outcomes computed';}
function blank(){frames=[];selected=null;evidence=null;$('evidence-results').textContent='No observations supplied. Business validation remains unestablished.';$('export-evidence').disabled=true;$('clock').textContent='Not started';$('run-identity').textContent='A fresh native run begins when you press Play or Step.';$('agents').className='agents-empty';$('agents').textContent='Employee agents will be initialized when you run the model.';$('checks').textContent='No checks executed yet.';$('events').textContent='No events executed yet.';$('inspect-title').textContent='Select a person or stage';$('inspector').textContent='Inspect the state generated by the native model.';$('queue-detail').textContent='Queues and completions appear only after execution.';['money-chart','queue-chart'].forEach(id=>{$(id).className='chart empty';$(id).textContent='Run to compute a trajectory';});renderMetrics();renderProcess();controls();}
function renderMetrics(m={}){$('kpis').innerHTML=[['Revenue',money(m.revenue)],['Operating contribution',money(m.contribution)],['Completed engagements',num(m.completed)],['Active engagements',num(m.backlog)],['Delivery utilization',percent(m.utilization)],['AI proficiency · licensed',percent(m.proficiency)]].map(([k,v])=>`<div class="kpi"><span>${k}</span><b>${v}</b></div>`).join('');}
function renderProcess(f){$('process').innerHTML=stageNames.map((name,i)=>{const q=f?.queues[i];return `<button class="stage ${q?.waiting>0?'pressure':''}" data-stage="${i}"><strong>${i+1}. ${name}</strong><b>${num(q?.waiting)}</b><span>waiting for a skilled person</span><span>${num(q?.assigned)} assigned · includes paused work</span></button>`;}).join('');if(f)$('queue-detail').textContent=`${num(f.metrics.prospects)} prospects → ${num(f.metrics.won)} won → ${num(f.metrics.completed)} completed. ${num(f.metrics.licensed)} licensed employees; ${num(f.metrics.ai_users)} have used AI. Assignments persist overnight.`;}
function chart(id,series,colors,format){const el=$(id);if(frames.length<2)return;const times=frames.map(f=>f.time),xmax=Math.max(...times,1),values=frames.flatMap(f=>series.map(k=>f.metrics[k]));const lo=Math.min(0,...values),hi=Math.max(...values,1),y=v=>120-(v-lo)/(hi-lo)*104;el.className='chart';el.innerHTML=`<svg viewBox="0 0 400 145" role="img" aria-label="${id==='money-chart'?'Computed cumulative revenue and operating costs':'Computed engagement backlog'}"><line x1="42" y1="120" x2="390" y2="120" stroke="#dbe5dc"/><text x="0" y="16" fill="#74867b" font-size="9">${esc(format(hi))}</text><text x="0" y="122" fill="#74867b" font-size="9">${esc(format(lo))}</text>${series.map((key,i)=>`<polyline fill="none" stroke="${colors[i]}" stroke-width="2" points="${frames.map(f=>`${42+f.time/xmax*348},${y(f.metrics[key])}`).join(' ')}"/>`).join('')}<text x="42" y="140" font-size="9" fill="#74867b">Start</text><text x="330" y="140" font-size="9" fill="#74867b">${num(xmax/24,1)} days</text></svg><div class="chart-key">${series.map((key,i)=>`<span style="color:${colors[i]}">● ${key==='cost'?'Operating cost':key==='revenue'?'Revenue':'Backlog'}</span>`).join(' · ')}</div>`;}
function inspector(){if(!session||!selected)return;const f=session.frame;let rows=[];if(selected.type==='agent'){const a=f.agents.find(a=>a.id===selected.id);$('inspect-title').textContent=`Employee ${a.id+1} · ${definition.levels[a.level].name}`;rows=[['State',stateNames[a.state]],['Primary skill',skillNames[a.skill]],['Second skill',a.second_skill<0?'None':skillNames[a.second_skill]],['Current engagement',a.job<0?'None':a.job+1],['AI license',a.licensed?'Yes':'No'],['Using AI now',a.using_ai?'Yes':'No'],['Proficiency',percent(a.proficiency)],['Delivery hours',num(a.delivery_hours,2)],['Training hours',num(a.training_hours,2)]];}else{const q=f.queues[selected.id];$('inspect-title').textContent=stageNames[selected.id];rows=[['Waiting',q.waiting],['Assigned / paused',q.assigned],['Oldest current wait',num(q.oldest_wait_hours,1)+' calendar hours'],['Mean wait before assignment',num(q.mean_wait_hours,1)+' calendar hours'],['Rule','FIFO among compatible tasks']];}$('inspector').innerHTML=rows.map(([k,v])=>`<div class="inspector-row"><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('');}
function render(view){session=view;const f=view.frame;if(frames.at(-1)?.time!==f.time)frames.push(f);$('clock').textContent=clock(f.time);$('run-identity').textContent=`Definition ${view.config_sha256.slice(0,10)} · seed ${definition.parameters.seed}`;renderMetrics(f.metrics);renderProcess(f);$('agents').className='agent-grid';$('agents').innerHTML=definition.levels.map((l,i)=>`<div class="agent-role"><b>${esc(l.name)} · ${l.count}<span class="range">${percent(f.levels[i].utilization)} delivery utilization</span></b><div>${f.agents.filter(a=>a.level===i).map(a=>`<button class="person ${stateClass[a.state]} ${a.licensed?'licensed':''} ${selected?.type==='agent'&&selected.id===a.id?'selected':''}" data-agent="${a.id}" aria-label="Employee ${a.id+1}, ${esc(l.name)}, ${stateNames[a.state]}" title="Employee ${a.id+1} · ${stateNames[a.state]}"></button>`).join('')}</div></div>`).join('');$('checks').innerHTML=f.checks.map(c=>`<details class="native-check"><summary><span>${esc(c.name)}</span><b class="${c.passed?'pass':'fail'}">${c.passed?'PASS':'FAIL'}</b></summary><div class="muted">Actual: ${num(c.actual,6)}<br>Expected: ${num(c.expected,6)}<br>Absolute gap: ${Math.abs(c.actual-c.expected).toExponential(2)}<br>Allowed gap: ${c.tolerance.toExponential(2)}</div></details>`).join('');$('events').innerHTML=[...f.events].reverse().slice(0,20).map(e=>`<div class="event"><time>${clock(e.time)}</time>${esc(e.text)}</div>`).join('')||'No events executed yet.';chart('money-chart',['revenue','cost'],['#17655a','#b78b52'],money);chart('queue-chart',['backlog'],['#5d8070'],num);inspector();if(view.status!=='paused')playing=false;controls();}
async function initialize(){if(session)return;definition=read();render(await api('/workshop/sessions',definition));form();}
async function advance(){if(pending)return;pending=true;controls();try{await initialize();if(session.status==='paused')render(await api(`/workshop/sessions/${session.id}/step`,{expected_revision:session.revision,hours:Number($('step-hours').value)}));}catch(e){playing=false;notice(e.message);}finally{pending=false;controls();}if(playing&&session?.status==='paused')timer=setTimeout(advance,Number($('pace').value));}
function pause(){playing=false;clearTimeout(timer);controls();}
async function reset(){pause();if(pending)return;if(session)await api(`/workshop/sessions/${session.id}/stop`,{});session=null;blank();form();notice();}
function experimentResults(){const e=experiment;if(!e)return;const p=catalog.parameters.find(p=>p.id===e.variable);$('experiment-status').textContent=`${e.status} · ${e.finished} / ${e.total} runs · ${e.config.parameters.days} calendar days · seeds ${e.config.parameters.seed}–${e.config.parameters.seed+e.replications-1}${e.error?' · '+e.error:''}`;$('experiment-progress').max=e.total;$('experiment-progress').value=e.finished;$('cancel-experiment').disabled=!['queued','running'].includes(e.status);$('run-experiment').disabled=['queued','running','cancelling'].includes(e.status);$('export-experiment').disabled=!e.results.length;
 if(!e.results.length)return;const summary=(rows,k,fmt)=>{const v=rows.map(r=>r.metrics[k]).filter(v=>v!=null);if(!v.length)return '—';return `${fmt(v.reduce((s,x)=>s+x,0)/v.length)}<span class="range">${fmt(Math.min(...v))} – ${fmt(Math.max(...v))}</span>`;};
 $('experiment-results').className='table-scroll';$('experiment-results').innerHTML=`<div class="experiment-note">${esc(p.label)} · ${esc(p.unit)}. Means with observed min–max across completed replications; these ranges are not confidence intervals. Paired contribution changes use only seeds completed in both scenarios. First listed value is the reference. This experiment retains its original definition even if the form changes.</div><table><thead><tr><th>Value / completed runs</th><th>Revenue</th><th>Contribution</th><th>Paired contribution change</th><th>Completed</th><th>Backlog</th><th>Utilization</th></tr></thead><tbody>${e.values.map(value=>{const rows=e.results.filter(r=>r.value===value);const paired=rows.map(r=>{const b=e.results.find(b=>b.value===e.values[0]&&b.seed===r.seed);return b?r.metrics.contribution-b.metrics.contribution:null;}).filter(v=>v!==null);return `<tr><td>${value}<span class="range">${rows.length}/${e.replications} runs</span></td><td>${summary(rows,'revenue',money)}</td><td>${summary(rows,'contribution',money)}</td><td>${paired.length?money(paired.reduce((s,x)=>s+x,0)/paired.length):'—'}</td><td>${summary(rows,'completed',v=>num(v,1))}</td><td>${summary(rows,'backlog',v=>num(v,1))}</td><td>${summary(rows,'utilization',percent)}</td></tr>`;}).join('')}</tbody></table>`;
}
async function pollExperiment(){if(!experiment)return;try{experiment=await api(`/workshop/experiments/${experiment.id}`);experimentResults();if(['queued','running','cancelling'].includes(experiment.status))setTimeout(pollExperiment,750);}catch(e){notice(e.message);$('run-experiment').disabled=false;}}
async function handle(action){notice();try{await action();}catch(e){notice(e.message);}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('go-run').onclick=()=>handle(async()=>{definition=read();tab('simulate');});
$('define').addEventListener('input',()=>{try{const c=read();$('headcount').textContent=c.levels.reduce((s,l)=>s+l.count,0);}catch{}});
$('play').onclick=()=>handle(async()=>{if(playing){pause();return;}playing=true;await advance();});$('step').onclick=()=>handle(advance);$('reset').onclick=()=>handle(reset);
$('agents').onclick=e=>{const b=e.target.closest('[data-agent]');if(!b||!session)return;selected={type:'agent',id:Number(b.dataset.agent)};inspector();};$('process').onclick=e=>{const b=e.target.closest('[data-stage]');if(!b||!session)return;selected={type:'stage',id:Number(b.dataset.stage)};inspector();};
$('export-definition').onclick=()=>handle(async()=>download('tr-practice-definition.json',read()));$('import-definition').onclick=()=>$('definition-file').click();$('definition-file').onchange=e=>handle(async()=>{const file=e.target.files[0];if(!file)return;if(file.size>100000)throw new Error('Definition must be smaller than 100 KB.');const c=JSON.parse(await file.text());if(!c.parameters||!Array.isArray(c.levels)||c.levels.length!==8||catalog.parameters.some(p=>!Number.isFinite(c.parameters[p.id]))||c.levels.some((l,i)=>l.name!==definition.levels[i].name||!Number.isInteger(l.count)||!Number.isFinite(l.rate)||!Number.isFinite(l.salary)))throw new Error('Use the exported practice-definition format.');definition=c;form();notice('Definition imported. Business constraints are checked before execution.');e.target.value='';});
$('export-run').onclick=()=>handle(async()=>{const r=await fetch(`/workshop/sessions/${session.id}/record`);if(!r.ok)throw new Error('Run export failed');download('tr-operating-run.json',await r.text(),true);});
$('experiment-variable').onchange=()=>{$('experiment-values').value=({license_share:'0, 0.1, 0.2, 0.3',ai_saving:'0, 0.2, 0.4',training_hours:'0, 2, 4',prospects_day:'4, 8, 12',review_extra:'0, 0.15, 0.4',bd_fraction:'0, 0.25, 0.5',secondary_skill:'0.1, 0.35, 0.7',win_rate:'0.2, 0.4, 0.6'})[$('experiment-variable').value];};
$('run-experiment').onclick=()=>handle(async()=>{const raw=$('experiment-values').value.split(',');if(raw.some(v=>!v.trim()))throw new Error('Each experiment value must be a number.');const values=raw.map(Number);experiment=await api('/workshop/experiments',{config:read(),variable:$('experiment-variable').value,values,replications:Number($('replications').value)});$('experiment-results').textContent='Waiting for the first completed run…';experimentResults();pollExperiment();});
$('cancel-experiment').onclick=()=>handle(async()=>{experiment=await api(`/workshop/experiments/${experiment.id}/cancel`,{});experimentResults();});$('export-experiment').onclick=()=>download('tr-operating-experiment.json',experiment);
$('evidence-template').onclick=()=>{const f=session?.frame;download('tr-observations-template.json',{source:'Replace with dataset name, vintage and observation-period alignment',kind:'observed',rows:[{time:f?.time||24,metric:'utilization',unit:'1',actual:null,tolerance:.05},{time:f?.time||24,metric:'completed',unit:'engagement',actual:null,tolerance:2}]});notice('Fill actual observations in the template. Time is hours from a Monday 00:00 start; revenue, hours and completions are cumulative, utilization is delivery / billable-role shift hours.');};
$('import-evidence').onclick=()=>handle(async()=>{if(!session)throw new Error('Run the model before attaching observations.');$('evidence-file').click();});$('evidence-file').onchange=e=>handle(async()=>{const file=e.target.files[0];if(!file)return;if(file.size>1000000)throw new Error('Evidence file must be under 1 MB.');evidence=await api(`/workshop/sessions/${session.id}/evidence`,JSON.parse(await file.text()));$('evidence-results').className='table-scroll';$('evidence-results').innerHTML=`<p class="${evidence.passed?'pass':'fail'}">${evidence.passed?'Within supplied tolerances':'Outside supplied tolerances'} · ${esc(evidence.kind)} · ${esc(evidence.source)}</p><table><thead><tr><th>Hour / metric</th><th>Observed</th><th>Simulated</th><th>Error / tolerance</th><th>Result</th></tr></thead><tbody>${evidence.rows.map(r=>`<tr><td>${r.time} / ${esc(r.metric)}</td><td>${num(r.actual,3)}</td><td>${num(r.predicted,3)}</td><td>${num(r.error,3)} / ${r.tolerance}</td><td class="${r.passed?'pass':'fail'}">${r.passed?'PASS':'FAIL'}</td></tr>`).join('')}</tbody></table>`;$('export-evidence').disabled=false;e.target.value='';});$('export-evidence').onclick=()=>download('tr-observation-comparison.json',evidence);
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('pagehide',()=>{if(session)fetch(`/workshop/sessions/${session.id}/stop`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}',keepalive:true});});
await handle(async()=>{catalog=await api('/workshop/catalog');definition=structuredClone(catalog.default);form();blank();$('experiment-variable').innerHTML=experimentChoices.map(k=>`<option value="${k}">${esc(catalog.parameters.find(p=>p.id===k).label)}</option>`).join('');$('methods').innerHTML=catalog.methods.map(m=>`<div class="method"><h3><span>${m.method}</span>${esc(m.name)}</h3><code>${esc(m.implementation)}</code><p>${esc(m.rule)}</p><div class="muted">${esc(m.evidence)}</div></div>`).join('');$('limitations').innerHTML=catalog.limitations.map(l=>`<li>${esc(l)}</li>`).join('');});

await handle(async()=>{const r=await api('/workshop/verification');$('verification-status').innerHTML=!r.available?'No test receipt recorded.':`<p class="${r.passed&&r.sources_current?'pass':'fail'}">${r.passed?'Recorded checks passed':'Recorded check failures'} · ${r.sources_current?'sources unchanged':'receipt predates source edits'}</p><p class="muted">${esc(r.scope)}</p>${r.checks.map(c=>`<div class="check"><span>${esc(c.command.at(-1))}</span><b>${c.exit_code===0&&c.passed!==false?'PASS':'FAIL'}</b></div>`).join('')}`;});
